language: python
python:
  - 3.7
services:
  - docker

install:
  - pip install -r requirements.txt # for dependencies

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # Login to dockerhub

script:
  # Unit testing needed here
  - docker build -t leersma/challenge-flask-api:latest . # building images with tag (-t)

deploy:
  provider: script
  script:
    docker push leersma/challenge-flask-api:latest; # pushing on docker hub
  on:
    branch: master # Only if branch is "master"